"""The ``.x0r`` document — Extract0r's own portable transcription container.

A plain ``.txt`` tab is what a player wants to print; ``.x0r`` is what the app needs
to reopen the session later: exact note timings, the tuning that was solved for, the
backends and versions that produced it, and the copyright attestation the uploader
agreed to. It is JSON so it stays diffable and inspectable.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from app.domain.notes import NoteEvent, StemKind, Transcription
from app.domain.tab.fretboard import Shape, Tuning
from app.domain.timing import TimingEstimate

X0R_SCHEMA_VERSION = "1.0"


@dataclass(slots=True)
class Provenance:
    """Who made this, with what, and under what claim of rights."""

    source_filename: str
    source_sha256: str
    separation_backend: str
    transcription_backend: str
    created_at: str = field(
        default_factory=lambda: datetime.now(UTC).isoformat(timespec="seconds")
    )
    rights_attestation: str = "user_asserted_ownership_or_fair_use"
    app_version: str = "0.1.0"


@dataclass(slots=True)
class X0rStem:
    stem: StemKind
    notation: str
    tuning: Tuning | None
    transcription: Transcription
    shapes: Sequence[Shape] = ()
    rendered_tab: str = ""


def _note_json(note: NoteEvent) -> dict[str, Any]:
    return {
        "start": round(note.start_s, 4),
        "end": round(note.end_s, 4),
        "pitch": note.pitch,
        "velocity": note.velocity,
        "confidence": round(note.confidence, 3),
    }


def _shape_json(shape: Shape) -> dict[str, Any]:
    return {
        "start": round(shape.start_s, 4),
        "positions": [
            {"string": p.string, "fret": p.fret, "pitch": p.note.pitch}
            for p in shape.positions
        ],
    }


def build(
    provenance: Provenance,
    stems: Sequence[X0rStem],
    timing: TimingEstimate | None = None,
) -> dict[str, Any]:
    """Assemble the in-memory document. Serialise it with :func:`dumps`."""
    return {
        "format": "x0r",
        "schema_version": X0R_SCHEMA_VERSION,
        "timing": (
            {
                "tempo_bpm": timing.tempo_bpm,
                "time_signature": list(timing.time_signature),
                "first_beat_s": timing.first_beat_s,
                "confidence": timing.confidence,
                "key": timing.key.name if timing.key else None,
                "key_confidence": timing.key.confidence if timing.key else None,
                "source": timing.source,
            }
            if timing
            else None
        ),
        "provenance": {
            "source_filename": provenance.source_filename,
            "source_sha256": provenance.source_sha256,
            "separation_backend": provenance.separation_backend,
            "transcription_backend": provenance.transcription_backend,
            "created_at": provenance.created_at,
            "rights_attestation": provenance.rights_attestation,
            "app_version": provenance.app_version,
        },
        "notice": (
            "Generated by Extract0r from user-supplied audio. The uploader asserted "
            "they hold the rights to that audio or that their use is otherwise lawful. "
            "This transcription may itself be a derivative work of a copyrighted "
            "composition; distribution may require a licence."
        ),
        "stems": [
            {
                "stem": s.stem.value,
                "notation": s.notation,
                "tuning": (
                    {
                        "name": s.tuning.name,
                        "open_pitches": list(s.tuning.open_pitches),
                        "fret_count": s.tuning.fret_count,
                    }
                    if s.tuning
                    else None
                ),
                "tempo_bpm": s.transcription.tempo_bpm,
                "time_signature": list(s.transcription.time_signature),
                "backend": s.transcription.backend,
                "notes": [_note_json(n) for n in s.transcription.sorted_notes()],
                "shapes": [_shape_json(sh) for sh in s.shapes],
                "rendered_tab": s.rendered_tab,
            }
            for s in stems
        ],
    }


def dumps(document: dict[str, Any]) -> str:
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def sha256_of(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()
